### ISSUE TITLE
建议增加密码认证功能提升安全性

### ISSUE THREAD

**Issue by Dongsh** [zanjie1999/meDisplay#1]
感谢项目，测试之后感觉非常好用。

有一个小建议：是否可以考虑为网页添加一个密码验证登录？密码可以使用启动命令或本地文件指定，这样可以增加共享局域网内使用的安全性。

谢谢！

**Comment by zanjie1999** [comment]
感觉很脱裤子放屁哦，防自己吗？连自己的局域网的安全都保护不了你还在乎安全吗

至于像公司网络这种公用网络，担心别人看到你屏幕的内容，那你可以完全不用担心，因为只有一个线程，你看着的时候别人绝对打不开
