### ISSUE TITLE
启动服务后选择显示器0或者显示器1都是黑屏无法显示

### ISSUE THREAD

**Issue by zzq-kuangyan** [zanjie1999/meDisplay#2]
终端报错如下：
192.168.0.107 - - [15/Oct/2024 19:04:24] "GET /v/1 HTTP/1.1" 200 -
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
2024-10-15 19:04:24.321 ffmpeg[10777:286501] WARNING: Add NSCameraUseContinuityCameraDeviceType to your Info.plist to use AVCaptureDeviceTypeContinuityCamera.
objc[10777]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
objc[10777]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
[AVFoundation indev @ 0x7fd399904c00] Configuration of video device failed, falling back to default.
[avfoundation @ 0x7fd399904800] Selected pixel format (yuv420p) is not supported by the input device.
[avfoundation @ 0x7fd399904800] Supported pixel formats:
[avfoundation @ 0x7fd399904800]   uyvy422
[avfoundation @ 0x7fd399904800]   yuyv422
[avfoundation @ 0x7fd399904800]   nv12
[avfoundation @ 0x7fd399904800]   0rgb
[avfoundation @ 0x7fd399904800]   bgr0
[avfoundation @ 0x7fd399904800] Overriding selected pixel format to use uyvy422 instead.

**Comment by zanjie1999** [comment]
你要给予屏幕录制的权限，第一次的时候会弹出来，如果你没有按照apple给的指引去启用的话，那你只能自己手动去设置中给予终端屏幕录制权限
